# Generated by Django 4.2.8 on 2023-12-29 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_post_datetime_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 23, 49, 56, 689580)),
        ),
    ]
